/** @type {import('tailwindcss').Config} */

const colors = require("tailwindcss/colors");
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,svelte}"],
  purge: {
    enabled: true,
    content: ["./src/**/*.{js,ts,jsx,tsx,svelte}"],
  },
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["IBM Plex Sans", "sans-serif"],
        display: ["Source Serif Pro", "Georgia", "serif"],
        body: ["Synonym", "system-ui", "sans-serif"],
      },
      colors: {
        transparent: "#0000",
        current: "currentColor",
        error: "rgb(var(--error) / <alpha-value>)",
        success: "rgb(var(--success) / <alpha-value>)",
        info: "rgb(var(--info) / <alpha-value>)",
        warning: "rgb(var(--warning) / <alpha-value>)",
        primary: {
          100: "rgb(var(--primary-100) / <alpha-value>)",
          200: "rgb(var(--primary-200) / <alpha-value>)",
          300: "rgb(var(--primary-300) / <alpha-value>)",
          400: "rgb(var(--primary-400) / <alpha-value>)",
          500: "rgb(var(--primary-500) / <alpha-value>)",
          600: "rgb(var(--primary-600) / <alpha-value>)",
          700: "rgb(var(--primary-700) / <alpha-value>)",
          800: "rgb(var(--primary-800) / <alpha-value>)",
          900: "rgb(var(--primary-900) / <alpha-value>)",
          DEFAULT: "rgb(var(--primary-500) / <alpha-value>)",
        },
        secondary: {
          100: "rgb(var(--secondary-100) / <alpha-value>)",
          200: "rgb(var(--secondary-200) / <alpha-value>)",
          300: "rgb(var(--secondary-300) / <alpha-value>)",
          400: "rgb(var(--secondary-400) / <alpha-value>)",
          500: "rgb(var(--secondary-500) / <alpha-value>)",
          600: "rgb(var(--secondary-600) / <alpha-value>)",
          700: "rgb(var(--secondary-700) / <alpha-value>)",
          800: "rgb(var(--secondary-800) / <alpha-value>)",
          900: "rgb(var(--secondary-900) / <alpha-value>)",
          DEFAULT: "rgb(var(--secondary-500) / <alpha-value>)",
        },
        gray: {
          50: "#fafafa",
          100: "#f4f4f5",
          150: "#ececee",
          200: "#e4e4e7",
          250: "#dcdcdf",
          300: "#d4d4d8",
          350: "#babac1",
          400: "#a1a1aa",
          450: "#898992",
          500: "#71717a",
          550: "#61616c",
          600: "#54545d",
          650: "#46464e",
          700: "#38383f",
          750: "#222227",
          800: "#18181c",
          850: "#0e0e10",
          900: "#000000",
        },
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
      },
      borderWidth: {
        1: "1px",
        2: "2px",
      },
      boxShadow: {
        "main-sm": "0 0 12px #0001",
        "main-md": "0 0 15px #0000001f",
        "main-lg": "0 0 20px #00000022",
        "glow-sm": "0 0 5px #2494ef33",
        "glow-md": "0 0 10px #2494ef44",
        "glow-lg": "0 0 15px #2494ef66",
      },
      fontSize: {
        xs: "12px",
        sm: "14px",
        base: "16px",
        DEFAULT: "16px",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem",
        "6xl": "4rem",
        "7xl": "5rem",
      },
    },
  },
  plugins: [require("tailwindcss-global-dark")],
};
